### ISSUE TITLE
Error when testing on VOC dataset

### ISSUE THREAD

**Issue by bowenc0221** [kuangliu/torchcv#40]
Hi, thanks for the great implementation. I tried to run the FPNSSD code, but I got this error when testing. I'm using python 2.7 and PyTorch 0.4.0. Any idea what might cause the problem? Thanks.

Traceback (most recent call last):
  File "eval.py", line 103, in <module>
    eval(net, dataset)
  File "eval.py", line 101, in eval
    iou_thresh=0.5, use_07_metric=True))
  File "/hdfs/input/detection/pytorch.fpnssd/torchcv/evaluations/voc_eval.py", line 25, in voc_eval
    gt_labels, gt_difficults, iou_thresh, use_07_metric)
  File "/hdfs/input/detection/pytorch.fpnssd/torchcv/evaluations/voc_eval.py", line 130, in eval_detection_voc
    iou_thresh=iou_thresh)
  File "/hdfs/input/detection/pytorch.fpnssd/torchcv/evaluations/voc_eval.py", line 231, in calc_detection_voc_prec_rec
    gt_difficult_l = gt_difficult[gt_mask_l]
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by bowenc0221** [comment]
solved

**Comment by TomLan42** [comment]
Hey, I met the same problem. How do you solve it?
